spring:
  redis:
    host: 146.56.98.218
    password: '*N2vya7H@muDTwdNMR!'
    database: '260'
    port: '6379'
  application:
    name: authorization-server
  profiles:
    active: prod
server:
  servlet:
    encoding:
      force: 'true'
      charset: UTF-8
  port: '8100'
springdoc:
  default-produces-media-type: application/json
  show-actuator: 'true'
  swagger-ui:
    disable-swagger-default-url: 'true'
    groups-order: desc
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: 'true'
  api-docs:
    path: /api-docs
  paths-to-match: /api/**
jwt:
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvp2rIum8ZCFGaWp06klve94eVEg+n1vfuk6lmeeUfoW7ek5lueK+jgN6CDNccaWOdQVuBw+VAAv3oQ61UE+sO+63MOVIQG/+ZxBtBvuiyiPP1viUt97tHB5uqgn9edhoQWQsyaYbAGBjQgant4PlCyDoYNlog0EbasXzi0xNYPMVoH9HUcqs2QRDtcRDKuSKVZIGo2ic9HzOsp+wiEfVt21YP8TXkZNjjc4J1y/DcJkW4tiQv+giJ6eeFgpLjyTy++FT51iQoeQMpvtofzwqUTXi7faj/DRJ2/PmlLSqE+H9e2alJYPPBTF6V3p9wdV+YQiLTfmTjV7NS/37ZVk6PwIDAQAB
  private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC+nasi6bxkIUZpanTqSW973h5USD6fW9+6TqWZ55R+hbt6TmW54r6OA3oIM1xxpY51BW4HD5UAC/ehDrVQT6w77rcw5UhAb/5nEG0G+6LKI8/W+JS33u0cHm6qCf152GhBZCzJphsAYGNCBqe3g+ULIOhg2WiDQRtqxfOLTE1g8xWgf0dRyqzZBEO1xEMq5IpVkgajaJz0fM6yn7CIR9W3bVg/xNeRk2ONzgnXL8NwmRbi2JC/6CInp54WCkuPJPL74VPnWJCh5Aym+2h/PCpRNeLt9qP8NEnb8+aUtKoT4f17ZqUlg88FMXpXen3B1X5hCItN+ZONXs1L/ftlWTo/AgMBAAECggEAGljLt1MsXYC17UswJtQIq0vb0FV+BmPaDDPjst6uCUDt1W1xpRxgr1tuqiSDQhgalTUvbJ1sQGnnC+VvDU895LjNrF38ux9fwBomn8D3Us5ZY4LPd4zCJFFWhX1FAmr1mhhBEow5jjdEcPNfij+aUIv3Yq+aQQ4mPn9m9tmQlnY18pNm8p2njq88NZEe4ib8hPpiEnJ0Mxq7CmN1AbdvINZKlbzrrWO0VKEjTwbGednRHd9elfYy4OgIDWs3HuxMdiA5mIvE6wc65B4GG4NoDiwkgOeLxvAkhBhTzXtKcEbjDRQYNXP6crdZAcBjWLo5KFzLPP+DEqpXfZlzncqWWQKBgQDhKTv1gTb6JVtFtBsD+Emr0rezS9fZMxP2kTE/O159fZkZd9gN8lGqCzhQUwz6sX2kvG6Ej9TLJGvWADxxyy8Mno6lWg3YhJ2+3rKI+00ql7AOY9/4zIwMR7dc7e2mhewaIoMPgiqm8y+AMpEAdA6boiNmGXgwZ9nJiFPsZxuQpwKBgQDYuS93O0IlknlG5YSqK8ieVP0HQTmBZcpIgY933bxCTVEwLvanKdnNvEB2t5xG7VyduQgKXqfFFdTmROECpAc2fGPxYYUQhQs9vAzXRrwK+GIaijp766ZkCQOqdBbPdDSsl860sf8Fi1ncm+DwFOLTIRMGGIxoL6OsV2KGRl7kqQKBgC+OV/2ohwYaccatHa+e92B1JxuVf0d+xE6lp/MlBPYYWwfICjgX4Cu8Ju7AO9OPPWxX6DfTcSxeyu/uKNYYBh3yN0qxVI9Qo0i3HJpWCZxfYW4IpjuUaFgHpbDZCALN8moqs+fIpF2Sq4u2Im4oFRXGDxf3dS00Igmw45jgxi+tAoGAb2Oe9dVLRixmkP3elegzEM31zwjDGbLLqUCOELmyzREYLX+13m0wOQIMz/fHJt1QwPAdJddIu49hAYldbRIJcwO0Cpho3/jBslU49FyywaCwK5voO1D/EGNhsvY/0xiTCjJsV4s03BCney/TCRJzErjpIjTz1YjGwwmW5hS9KSECgYBQ0sDYrEiUxJaX+dMtT7ieMLGGeVq6SUiF3esoXRIDJlwCchVyG96M7E+D3aECoatPOKKgLgogg6zNW/VaUaZ3S2ayHK6xiZjv6e1NbzsWnZdb/YoCl2lmuEXxtJWTCIWJ1uWY9xRf5rtNlXCI91ENr4oUXfzvYOD1YOA+llP6fQ==
  refresh:
    expiry-time: '1'
  access:
    expiry-time: '3600'
eureka:
  client:
    register-with-eureka: 'true'
    fetch-registry: 'true'
management:
  endpoints:
    web:
      exposure:
        include: beans, conditions, configprops, env, health, httpexchanges, info, loggers, metrics, mappings, threaddump, shutdown
      base-path: /auth-server/manage
  endpoint:
    health:
      show-details: always
